# cpp_generator.py -- Write UE4.27-compatible C++ class files from CppClassSpec.
from __future__ import annotations
import os
from typing import Any, Dict, List, Tuple

from mcp_bridge.generation.spec_schema import CppClassSpec


# Map parent class names to the include path needed
_PARENT_INCLUDES: Dict[str, str] = {
    "AActor": "GameFramework/Actor.h",
    "APawn": "GameFramework/Pawn.h",
    "ACharacter": "GameFramework/Character.h",
    "APlayerController": "GameFramework/PlayerController.h",
    "AGameModeBase": "GameFramework/GameModeBase.h",
    "AGameMode": "GameFramework/GameMode.h",
    "AGameStateBase": "GameFramework/GameStateBase.h",
    "AHud": "GameFramework/HUD.h",
    "AAIController": "AIController.h",
    "UGameInstance": "Engine/GameInstance.h",
    "UActorComponent": "Components/ActorComponent.h",
    "USceneComponent": "Components/SceneComponent.h",
    "USaveGame": "GameFramework/SaveGame.h",
}

_PREFIX_MAP: Dict[str, str] = {
    "Actor": "A", "Pawn": "A", "Character": "A", "PlayerController": "A",
    "GameModeBase": "A", "GameMode": "A", "GameStateBase": "A", "HUD": "A",
    "AIController": "A", "GameInstance": "U", "ActorComponent": "U",
    "SceneComponent": "U", "SaveGame": "U",
}


def _normalize_parent(parent: str) -> str:
    """Add the UE4 class prefix if not already present."""
    if parent[:1] in ("A", "U", "F", "I"):
        return parent
    prefix = _PREFIX_MAP.get(parent, "A")
    return f"{prefix}{parent}"


def _get_include(parent: str) -> str:
    return _PARENT_INCLUDES.get(parent, "GameFramework/Actor.h")


def generate_header(spec: CppClassSpec, project_name: str = "Game") -> str:
    """Generate a .h file for the given spec."""
    parent = _normalize_parent(spec.parent_class)
    include = _get_include(parent)
    class_name = spec.name if spec.name[:1] in ("A", "U", "F") else f"A{spec.name}"
    api_macro = f"{project_name.upper()}_API"

    lines = [
        f"// {spec.name}.h -- Generated by PromptBrush",
        f"// Parent: {parent}",
        "#pragma once",
        "",
        "#include \"CoreMinimal.h\"",
        f"#include \"{include}\"",
        f"#include \"{spec.name}.generated.h\"",
        "",
        "UCLASS()",
        f"class {api_macro} {class_name} : public {parent}",
        "{",
        "    GENERATED_BODY()",
        "",
        "public:",
        f"    {class_name}();",
    ]

    for func in spec.functions:
        lines.append("")
        lines.append("    UFUNCTION(BlueprintCallable, Category=\"Generated\")")
        lines.append(f"    void {func}();")

    lines += [
        "",
        "protected:",
        "    virtual void BeginPlay() override;",
        "",
        "public:",
        "    virtual void Tick(float DeltaTime) override;",
        "};",
        "",
    ]
    return "\n".join(lines)


def generate_source(spec: CppClassSpec) -> str:
    """Generate a .cpp file for the given spec."""
    class_name = spec.name if spec.name[:1] in ("A", "U", "F") else f"A{spec.name}"

    lines = [
        f"// {spec.name}.cpp -- Generated by PromptBrush",
        f"#include \"{spec.name}.h\"",
        "",
        f"{class_name}::{class_name}()",
        "{",
        "    PrimaryActorTick.bCanEverTick = true;",
        "}",
        "",
        f"void {class_name}::BeginPlay()",
        "{",
        "    Super::BeginPlay();",
        "}",
        "",
        f"void {class_name}::Tick(float DeltaTime)",
        "{",
        "    Super::Tick(DeltaTime);",
        "}",
    ]

    for func in spec.functions:
        lines += [
            "",
            f"void {class_name}::{func}()",
            "{",
            f"    // TODO: implement {func}",
            "}",
        ]

    lines.append("")
    return "\n".join(lines)


def write_cpp_class(
    spec: CppClassSpec, project_source_root: str
) -> Tuple[bool, str, Dict[str, Any]]:
    """Write .h and .cpp files for a CppClassSpec to disk.

    Does not overwrite existing files.
    """
    try:
        target_dir = os.path.join(project_source_root, spec.source_path)
        os.makedirs(target_dir, exist_ok=True)

        h_path = os.path.join(target_dir, f"{spec.name}.h")
        cpp_path = os.path.join(target_dir, f"{spec.name}.cpp")

        if os.path.exists(h_path):
            return True, "", {"h_path": h_path, "cpp_path": cpp_path, "skipped": True}

        # Infer project name from directory structure
        parts = project_source_root.replace("\\", "/").rstrip("/").split("/")
        project_name = parts[-2] if len(parts) >= 2 else "Game"

        with open(h_path, "w", encoding="utf-8") as f:
            f.write(generate_header(spec, project_name))

        with open(cpp_path, "w", encoding="utf-8") as f:
            f.write(generate_source(spec))

        return True, "", {"h_path": h_path, "cpp_path": cpp_path, "skipped": False}

    except Exception as e:
        return False, str(e), {}


def write_all_cpp_classes(
    specs: List[CppClassSpec], project_source_root: str
) -> Dict[str, Any]:
    results = []
    errors: List[str] = []
    for spec in specs:
        if not spec.generate_cpp:
            continue
        ok, err, data = write_cpp_class(spec, project_source_root)
        entry: Dict[str, Any] = {"name": spec.name, "success": ok, "data": data}
        if err:
            entry["error"] = err
            errors.append(f"{spec.name}: {err}")
        results.append(entry)
    return {
        "results": results,
        "errors": errors,
        "total": len(results),
        "succeeded": sum(1 for r in results if r["success"]),
    }
